// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: protocols/message.proto

package protocols

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageFoo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Index   int64  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Foo     string `protobuf:"bytes,3,opt,name=foo,proto3" json:"foo,omitempty"`
	Messge  string `protobuf:"bytes,4,opt,name=messge,proto3" json:"messge,omitempty"`
}

func (x *MessageFoo) Reset() {
	*x = MessageFoo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageFoo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageFoo) ProtoMessage() {}

func (x *MessageFoo) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageFoo.ProtoReflect.Descriptor instead.
func (*MessageFoo) Descriptor() ([]byte, []int) {
	return file_protocols_message_proto_rawDescGZIP(), []int{0}
}

func (x *MessageFoo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MessageFoo) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *MessageFoo) GetFoo() string {
	if x != nil {
		return x.Foo
	}
	return ""
}

func (x *MessageFoo) GetMessge() string {
	if x != nil {
		return x.Messge
	}
	return ""
}

type MessageBar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Index   int64  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Bar     string `protobuf:"bytes,3,opt,name=bar,proto3" json:"bar,omitempty"`
	Messge  string `protobuf:"bytes,4,opt,name=messge,proto3" json:"messge,omitempty"`
}

func (x *MessageBar) Reset() {
	*x = MessageBar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageBar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageBar) ProtoMessage() {}

func (x *MessageBar) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageBar.ProtoReflect.Descriptor instead.
func (*MessageBar) Descriptor() ([]byte, []int) {
	return file_protocols_message_proto_rawDescGZIP(), []int{1}
}

func (x *MessageBar) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MessageBar) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *MessageBar) GetBar() string {
	if x != nil {
		return x.Bar
	}
	return ""
}

func (x *MessageBar) GetMessge() string {
	if x != nil {
		return x.Messge
	}
	return ""
}

var File_protocols_message_proto protoreflect.FileDescriptor

var file_protocols_message_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x73, 0x22, 0x66, 0x0a, 0x0a, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x46,
	0x6f, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x6f, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x66, 0x6f, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x73, 0x73, 0x67, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x73, 0x73, 0x67, 0x65, 0x22, 0x66, 0x0a, 0x0a,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x61, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x61,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x62, 0x61, 0x72, 0x12, 0x16, 0x0a, 0x06,
	0x6d, 0x65, 0x73, 0x73, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65,
	0x73, 0x73, 0x67, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protocols_message_proto_rawDescOnce sync.Once
	file_protocols_message_proto_rawDescData = file_protocols_message_proto_rawDesc
)

func file_protocols_message_proto_rawDescGZIP() []byte {
	file_protocols_message_proto_rawDescOnce.Do(func() {
		file_protocols_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocols_message_proto_rawDescData)
	})
	return file_protocols_message_proto_rawDescData
}

var file_protocols_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protocols_message_proto_goTypes = []interface{}{
	(*MessageFoo)(nil), // 0: protocols.MessageFoo
	(*MessageBar)(nil), // 1: protocols.MessageBar
}
var file_protocols_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocols_message_proto_init() }
func file_protocols_message_proto_init() {
	if File_protocols_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocols_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageFoo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocols_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageBar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocols_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocols_message_proto_goTypes,
		DependencyIndexes: file_protocols_message_proto_depIdxs,
		MessageInfos:      file_protocols_message_proto_msgTypes,
	}.Build()
	File_protocols_message_proto = out.File
	file_protocols_message_proto_rawDesc = nil
	file_protocols_message_proto_goTypes = nil
	file_protocols_message_proto_depIdxs = nil
}
